/**
 * Topology gallery (§4): one card per space. Every image is generated by us from the same
 * face-pairing data the walker uses:
 *  - gluing diagram: the fundamental polyhedron (actual vertices/faces from topology/domain.ts)
 *    in orthographic projection, faces filled by pair colour (the same colours tint the walls
 *    in-world), with the pairing's twist angle or a flip glyph for mirrored pairs;
 *  - inside view: a thumbnail rendered by our renderer from a fixed camera inside the space.
 * Card text: name, curvature badge, orientability, one-line hint.
 */
import { type Domain, DOMAIN_IDS, makeDomain, type DomainId } from "../topology/domain";
import { type V4, apply, mul, inverse, translationByVector, toConformal } from "../geometry/space";
import { Renderer } from "../render/renderer";

const PAIR = Renderer.PAIR_COLOURS;
const css = (c: [number, number, number], a = 1) => `rgba(${Math.round(c[0] * 255)},${Math.round(c[1] * 255)},${Math.round(c[2] * 255)},${a})`;

/** Rotation/reflection part of the pairing relative to the pure translation across the face. */
export function pairingTwist(d: Domain, f: number): { angleDeg: number; mirrored: boolean } {
  const F = d.faces[f];
  const T = translationByVector(d.kappa, [-2 * F.dist * F.dir[0], -2 * F.dist * F.dir[1], -2 * F.dist * F.dir[2]]);
  const R = mul(inverse(d.kappa, T), F.g); // should be block-diag(1, R3)
  const m = (r: number, c: number) => R[4 * (c + 1) + 1 + r];
  const det = m(0, 0) * (m(1, 1) * m(2, 2) - m(1, 2) * m(2, 1)) - m(0, 1) * (m(1, 0) * m(2, 2) - m(1, 2) * m(2, 0)) + m(0, 2) * (m(1, 0) * m(2, 1) - m(1, 1) * m(2, 0));
  const tr = m(0, 0) + m(1, 1) + m(2, 2);
  const mirrored = det < 0;
  // proper rotation: tr = 1 + 2cos θ. (A reflection composed with a rotation has tr = −1 + 2cos θ; we
  // only report "mirrored" for those — the glyph shows a flip.)
  const angle = mirrored ? 0 : Math.acos(Math.max(-1, Math.min(1, (tr - 1) / 2))) * (180 / Math.PI);
  return { angleDeg: angle, mirrored };
}

/** Orthographic projection of the polyhedron (conformal coordinates, viewed from a tilted direction). */
export function gluingDiagramSvg(d: Domain, size = 150): string {
  const verts = d.vertices.map((v) => toConformal(v));
  const scale = Math.max(...verts.map((v) => Math.hypot(v[0], v[1], v[2]))) || 1;
  // view: rotate by yaw 35°, tilt 25° then drop depth
  const ya = (35 * Math.PI) / 180, ta = (25 * Math.PI) / 180;
  const proj = (v: Float64Array) => {
    const x = v[0] * Math.cos(ya) - v[2] * Math.sin(ya), z = v[0] * Math.sin(ya) + v[2] * Math.cos(ya), y = v[1];
    const y2 = y * Math.cos(ta) - z * Math.sin(ta), z2 = y * Math.sin(ta) + z * Math.cos(ta);
    return { x: size / 2 + (x / scale) * size * 0.38, y: size / 2 - (y2 / scale) * size * 0.38, depth: z2 };
  };
  const faces = d.faces.map((F, f) => {
    const onFace = d.vertices.map((v, i) => ({ v, i })).filter(({ v }) => Math.abs(F.w[0] * v[0] + F.w[1] * v[1] + F.w[2] * v[2] + F.w[3] * v[3]) < 1e-6);
    // order around the face centre in its frame
    const pts = onFace.map(({ v, i }) => { const l = apply(F.invFrame, v); return { i, ang: Math.atan2(l[2], l[1]) }; }).sort((a, b) => a.ang - b.ang).map((p) => p.i);
    const poly = pts.map((i) => proj(verts[i]));
    const depth = poly.reduce((a, p) => a + p.depth, 0) / poly.length;
    const centre = proj(toConformal(F.centre));
    // visible if the outward normal points toward the viewer: use the projected centre depth vs polyhedron centre
    const normalDepth = proj(toConformal(F.centre)).depth - proj(new Float64Array([0, 0, 0])).depth;
    return { f, poly, depth, centre, visible: normalDepth < 0, pair: Math.floor(f / 2) };
  });
  faces.sort((a, b) => b.depth - a.depth); // far first
  let svg = `<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 ${size} ${size}" width="${size}" height="${size}">`;
  svg += `<rect width="${size}" height="${size}" fill="#0b0d14"/>`;
  for (const fc of faces) {
    const col = PAIR[fc.pair % PAIR.length];
    const path = fc.poly.map((p, i) => `${i ? "L" : "M"}${p.x.toFixed(1)},${p.y.toFixed(1)}`).join(" ") + " Z";
    svg += `<path d="${path}" fill="${css(col, fc.visible ? 0.55 : 0.12)}" stroke="${css(col, fc.visible ? 1 : 0.35)}" stroke-width="1.2" ${fc.visible ? "" : 'stroke-dasharray="3 3"'}/>`;
  }
  // twist / flip glyphs: one per pair, drawn on whichever member of the pair is visible
  const drawn = new Set<number>();
  for (const fc of faces) {
    if (!fc.visible || drawn.has(fc.pair)) continue;
    drawn.add(fc.pair);
    const { angleDeg, mirrored } = pairingTwist(d, fc.f);
    const c = fc.centre;
    if (mirrored) {
      svg += `<g transform="translate(${c.x.toFixed(1)},${c.y.toFixed(1)})"><path d="M-7,-6 L-1,0 L-7,6 Z" fill="#fff"/><path d="M7,-6 L1,0 L7,6 Z" fill="none" stroke="#fff" stroke-width="1.2"/><line x1="0" y1="-8" x2="0" y2="8" stroke="#fff" stroke-dasharray="2 2"/></g>`;
    } else if (angleDeg > 0.5) {
      svg += `<g transform="translate(${c.x.toFixed(1)},${c.y.toFixed(1)})"><path d="M-7,0 A7,7 0 1,1 4,5.7" fill="none" stroke="#fff" stroke-width="1.5"/><path d="M1,7.5 L5.5,6.2 L3.4,2.3 Z" fill="#fff"/><text x="9" y="4" font-size="9" fill="#fff" font-family="ui-monospace,monospace">${Math.round(angleDeg)}°</text></g>`;
    } else {
      svg += `<g transform="translate(${c.x.toFixed(1)},${c.y.toFixed(1)})"><line x1="-7" y1="0" x2="7" y2="0" stroke="#fff" stroke-width="1.5"/><path d="M7,0 L3,-3 L3,3 Z" fill="#fff"/></g>`;
    }
  }
  svg += `</svg>`;
  return svg;
}

export interface GalleryCard { id: DomainId; name: string; badge: string; orientable: string; hint: string; svg: string }

export function buildCards(flatHalf: [number, number, number]): GalleryCard[] {
  return DOMAIN_IDS.map((id) => {
    const d = makeDomain(id, flatHalf);
    if (!d) return { id, name: "Open space", badge: "any", orientable: "—", hint: "no tiling: bend the geometry with the slider", svg: `<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 150 150" width="150" height="150"><rect width="150" height="150" fill="#0b0d14"/><circle cx="75" cy="75" r="40" fill="none" stroke="#88a" stroke-dasharray="4 4"/><text x="75" y="80" text-anchor="middle" fill="#aab" font-size="12" font-family="ui-monospace,monospace">∞</text></svg>` };
    return { id, name: d.name, badge: d.kappa < 0 ? "H³" : d.kappa > 0 ? "S³" : "E³", orientable: d.orientable ? "orientable" : "non-orientable", hint: d.hint, svg: gluingDiagramSvg(d) };
  });
}

export class Gallery {
  el: HTMLDivElement;
  thumbs = new Map<DomainId, string>();
  constructor(root: HTMLElement, readonly cards: GalleryCard[], readonly onPick: (id: DomainId) => void) {
    this.el = document.createElement("div");
    this.el.style.cssText = "position:fixed;inset:0;background:rgba(3,4,8,.82);backdrop-filter:blur(10px);display:none;align-items:center;justify-content:center;font-family:Inter,ui-sans-serif,system-ui,sans-serif;color:#e9ecf3;z-index:20";
    root.appendChild(this.el);
    this.render();
  }
  render(hideNames = false) {
    const grid = this.cards.map((c) => {
      const thumb = this.thumbs.get(c.id);
      return `<div data-id="${c.id}" class="gcard" style="background:rgba(22,25,38,.9);border-radius:14px;padding:12px;width:208px;cursor:pointer;border:1px solid rgba(255,255,255,.08);transition:border-color .15s,transform .15s" onmouseover="this.style.borderColor='rgba(255,207,106,.6)';this.style.transform='translateY(-2px)'" onmouseout="this.style.borderColor='rgba(255,255,255,.08)';this.style.transform=''">
        <div style="display:flex;gap:8px;align-items:center;margin-bottom:8px"><span style="background:${c.badge === "H³" ? "#2a5bd7" : c.badge === "S³" ? "#d7742a" : c.badge === "E³" ? "#3f8f4a" : "#555"};padding:2px 7px;border-radius:6px;font-size:11px;font-weight:600">${c.badge}</span><b style="font-size:13px">${hideNames ? "?" : c.name}</b></div>
        <div style="display:flex;gap:6px"><div style="border-radius:8px;overflow:hidden;width:92px;height:92px">${c.svg.replace('width="150" height="150"', 'width="92" height="92"')}</div><div style="width:92px;height:92px;background:#000;border-radius:8px;overflow:hidden">${thumb ? `<img src="${thumb}" style="width:92px;height:92px;object-fit:cover">` : '<div style="color:#667;font-size:10px;padding:34px 6px;text-align:center">rendering…</div>'}</div></div>
        <div style="font-size:10.5px;color:#9aa3b5;margin-top:8px">${hideNames ? "" : c.orientable}</div>
        <div style="font-size:11.5px;color:#d8dde8;margin-top:3px;line-height:1.4">${hideNames ? "identify this space by walking through it" : c.hint}</div></div>`;
    }).join("");
    this.el.innerHTML = `<div style="max-width:1140px;padding:10px"><div style="display:flex;justify-content:space-between;align-items:flex-end;margin-bottom:14px"><div><h3 style="margin:0;font-size:22px;font-weight:700">Choose a universe</h3><div style="font-size:12.5px;color:#9aa3b5;margin-top:4px">Gluing diagrams and thumbnails are generated from the same face-pairing data the ray walker uses; the coloured walls in-world match the diagram.</div></div><button id="galleryClose" style="background:rgba(255,255,255,.08);color:#e9ecf3;border:1px solid rgba(255,255,255,.1);padding:8px 14px;border-radius:10px;cursor:pointer;font-family:inherit">Close</button></div><div style="display:flex;flex-wrap:wrap;gap:12px">${grid}</div></div>`;
    this.el.querySelectorAll<HTMLElement>(".gcard").forEach((c) => c.addEventListener("click", () => { this.onPick(c.dataset.id as DomainId); this.hide(); }));
    this.el.querySelector("#galleryClose")!.addEventListener("click", () => this.hide());
  }
  show() { this.el.style.display = "flex"; }
  hide() { this.el.style.display = "none"; }
  toggle() { this.el.style.display === "flex" ? this.hide() : this.show(); }
  get visible() { return this.el.style.display === "flex"; }
  setThumb(id: DomainId, dataUrl: string) { this.thumbs.set(id, dataUrl); this.render(); }
}
export const _u = { V4: null as unknown as V4 };
